// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EF_Models
{
    public partial class ActivityExecutionStatusEvent
    {
        public long ActivityExecutionStatusEventId { get; set; }
        public long WorkflowInstanceInternalId { get; set; }
        public int EventOrder { get; set; }
        public long ActivityInstanceId { get; set; }
        public byte ExecutionStatusId { get; set; }
        public DateTime EventDateTime { get; set; }
        public DateTime DbEventDateTime { get; set; }
    }
}