// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EF_Models
{
    public partial class ActivityExecutionStatus
    {
        public byte ExecutionStatusId { get; set; }
        public string Description { get; set; }
    }
}