// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EF_Models
{
    public partial class Activity
    {
        public int WorkflowTypeId { get; set; }
        public string QualifiedName { get; set; }
        public int ActivityTypeId { get; set; }
        public string ParentQualifiedName { get; set; }
    }
}