// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EF_Models
{
    public partial class ActivityInstance
    {
        public long WorkflowInstanceInternalId { get; set; }
        public long ActivityInstanceId { get; set; }
        public string QualifiedName { get; set; }
        public Guid ContextGuid { get; set; }
        public Guid? ParentContextGuid { get; set; }
        public long? WorkflowInstanceEventId { get; set; }
    }
}