// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EF_Models
{
    public partial class CompletedScope
    {
        public Guid UidInstanceId { get; set; }
        public Guid CompletedScopeId { get; set; }
        public byte[] State { get; set; }
        public DateTime Modified { get; set; }
    }
}