// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EF_Models
{
    public partial class DefaultTrackingProfile
    {
        public string Version { get; set; }
        public string TrackingProfileXml { get; set; }
        public DateTime InsertDateTime { get; set; }
    }
}